# Стадия сборки
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install vite@4.5.0 svelte@4.2.7 @sveltejs/vite-plugin-svelte@2.4.5

COPY . .
RUN npm run build 

# Стадия запуска
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html
COPY /nginx/default.conf /etc/nginx/conf.d/default.conf
COPY /https-keys /etc/nginx/certs

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]