version: '3.9'

services:
  backend:

    container_name: backend
    build: ./backend

    environment:
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: app_user
      DB_PASSWORD: securepassword
      DB_NAME: app_db

    ports:
      - "8080:8080"
    networks:
      - shared_network
  

  nginx-frontend:

    container_name: nginx-frontend
    build: ./frontend

    depends_on:
      - backend

    ports:
      - "443:443"
      - "80:80"

    networks:
      - shared_network

  # nginx:
  #   container_name: nginx
  #   image: nginx:alpine

  #   volumes:
  #     - ./frontend/dist:/usr/share/nginx/html:ro
  #     - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./https-keys:/etc/nginx/certs

  #   ports:
  #     - "443:443"
  #     - "80:80"

  #   depends_on:
  #     - frontend

  #   networks:
  #     - shared_network


networks:
  shared_network:
    external: true 
    name: shared_connection

    