version: '3.8'

services:
  postgres:
    build: .
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - shared_network

volumes:
  pg_data:


networks:
  shared_network:
    external: true
    name: shared_connection
    driver: bridge
